import { ArrowRight, ArrowUpRight, Bookmark, Check, Handshake, Lightbulb, LockKeyhole, MessageCircle, Sprout } from "lucide-react";
import MarketingMotion from "../components/marketing-motion";
import MarketingSpecialties from "../components/marketing-specialties";
import LegacyWorkspaceLinks from "../components/legacy-workspace-links";
import "./marketing.css";
export default function Home() {
  return <div className="marketing"><LegacyWorkspaceLinks/><MarketingMotion/>
    <header className="marketing-nav"><a className="marketing-brand" href="/" aria-label="FirstSignal home"><img src="/firstsignal-logo.png" width="38" height="38" alt=""/>FirstSignal</a><nav aria-label="Main navigation"><a href="#why-firstsignal">Why FirstSignal</a><a href="#how-it-works">How it works</a><a href="#founders">For founders</a><a href="#investors">For investors</a></nav><a className="marketing-nav-cta" href="/app">Explore startups <ArrowUpRight size={17}/></a></header>
    <main id="main-content"><section className="marketing-hero"><div className="marketing-hero-copy"><span className="marketing-kicker">EARLY IDEAS. MEANINGFUL CONNECTIONS.</span><h1>Before the product.<br/>Before the pitch.<br/><em>The first signal.</em></h1><p>Share your progress and connect with founders and investors at your stage.</p><div className="marketing-actions"><a className="marketing-primary" href="/signin?return_to=%2Fapp%23profiles">Create a profile <ArrowRight size={18}/></a><a className="marketing-secondary" href="/app">Explore startups <ArrowUpRight size={17}/></a></div><p className="marketing-caption">For ideas, first prototypes, and early traction.</p></div>
    <div className="marketing-preview" aria-label="Illustrative founder profile and introduction workflow"><div className="marketing-preview-top"><span><Sprout size={16}/> A startup at a glance</span><span>SAMPLE PROFILE</span></div><article className="marketing-sample"><div className="marketing-sample-head"><span className="marketing-sample-avatar">T</span><div><strong>Tracegrid</strong><span>Bengaluru · Sample profile</span></div><Bookmark size={20}/></div><span className="marketing-chip">Manufacturing SaaS · Pre-product</span><h2>A clearer handover for small manufacturing teams.</h2><div className="marketing-evidence"><span>THE FIRST PROOF</span><p>16 interviews with supervisors at 6 factories</p><small>Sample data</small></div><div className="marketing-milestone"><span>THE NEXT MILESTONE</span><p>Test an offline-capable prototype with 2 consenting factories.</p></div><a href="/app?profile=tracegrid" className="marketing-profile-link">Explore the sample <ArrowRight size={17}/></a></article><div className="marketing-connection"><span className="marketing-connection-icon"><Handshake size={23}/></span><div><strong>Connect by mutual consent.</strong><p>Both people choose to connect.</p></div><Check size={18}/></div></div></section>
    <div className="marketing-principles"><span>Progress before polish.</span><span>Evidence before hype.</span><span>Conversation before commitment.</span></div>
    <MarketingSpecialties/><section className="marketing-process marketing-section" id="how-it-works"><div className="marketing-section-heading"><span className="marketing-kicker">HOW IT WORKS</span><h2>Three steps.<br/>One useful connection.</h2><p>Create a profile, find relevant people, and request an introduction.</p></div><div className="marketing-steps">{[{n:"01",icon:Lightbulb,title:"Create your profile.",text:"Describe your idea, progress, and next milestone."},{n:"02",icon:Bookmark,title:"Find relevant people.",text:"Browse by sector and stage. Save profiles that interest you."},{n:"03",icon:MessageCircle,title:"Request an introduction.",text:"Share why you’d like to connect. Chat opens after acceptance."}].map(({n,icon:Icon,title,text})=><article key={n}><div><span>{n}</span><Icon size={22}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="marketing-audiences marketing-section"><article id="founders"><figure className="marketing-audience-art"><img src="/images/founder-work-photo.webp" width="1400" height="788" loading="lazy" decoding="async" alt="A woman working on a laptop beside project notes in an office"/><figcaption className="marketing-photo-credit">Stock photo · <a href="https://unsplash.com/photos/woman-working-on-laptop-in-modern-office-setting-O9PEo38zOss" target="_blank" rel="noreferrer">Vitaly Gariev / Unsplash</a></figcaption></figure><span className="marketing-kicker">FOR FOUNDERS</span><h2>Show your progress.</h2><p>Present your idea, evidence, and next milestone in one profile.</p><ul><li><Check size={17}/>Tell your story with a structured profile.</li><li><Check size={17}/>Save a private draft until you’re ready.</li><li><Check size={17}/>Share your next milestone and funding intent.</li></ul><a className="marketing-primary" href="/signin?return_to=%2Fapp%23profiles">Create your founder profile <ArrowRight size={18}/></a></article><article id="investors"><figure className="marketing-audience-art"><img src="/images/project-discussion-photo.webp" width="1400" height="788" loading="lazy" decoding="async" alt="Two colleagues discussing a project together at a laptop"/><figcaption className="marketing-photo-credit">Stock photo · <a href="https://unsplash.com/photos/two-colleagues-collaborating-on-a-project-at-a-laptop-tRvuRPE8cr4" target="_blank" rel="noreferrer">Vitaly Gariev / Unsplash</a></figcaption></figure><span className="marketing-kicker">FOR INVESTORS</span><h2>Discover early teams.</h2><p>Explore founders’ experience, customer learning, and next steps.</p><ul><li><Check size={17}/>Browse by sector and development stage.</li><li><Check size={17}/>Share your interests in an investor profile.</li><li><Check size={17}/>Choose which introductions to accept.</li></ul><a className="marketing-secondary" href="/app#discover">Explore founder profiles <ArrowRight size={18}/></a></article></section>
    <section className="marketing-trust marketing-section"><div><span className="marketing-kicker">CLARITY BUILDS TRUST</span><h2>Early doesn’t have<br/>to mean unclear.</h2><a href="/app" className="marketing-secondary">Explore profiles <ArrowUpRight size={17}/></a></div><div className="marketing-trust-list">{[{icon:Sprout,title:"Claims stay in context.",text:"Profile claims are self-reported. Sample profiles are labelled."},{icon:LockKeyhole,title:"You choose what to share.",text:"Keep drafts private. List your profile when ready. Conversations stay with their participants."},{icon:Handshake,title:"Interest is a beginning.",text:"An introduction is not a funding commitment. FirstSignal does not process investments."}].map(({icon:Icon,title,text})=><article key={title}><Icon size={23}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section className="marketing-faq marketing-section"><div className="marketing-section-heading"><span className="marketing-kicker">FAQ</span><h2>Before you begin.</h2></div><div>{[{q:"Do I need a finished product?",a:"No. Ideas, prototypes, and early-stage projects are welcome."},{q:"Will FirstSignal get my startup funded?",a:"No funding is guaranteed. FirstSignal helps you connect; investment decisions and agreements happen independently."},{q:"Can anyone join right now?",a:"Yes. Create an account to save profiles, publish your own, and request introductions."},{q:"Are the sample founders and investors real?",a:"Sample profiles are fictional. Notes on samples stay private and contact nobody. Member introductions require acceptance."}].map(({q,a})=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
    <section className="marketing-closing"><span className="marketing-kicker">GET STARTED</span><h2>Bring your idea.<br/>Show your first signal.</h2><p>Create your profile and find your next connection.</p><a className="marketing-primary" href="/app">Explore FirstSignal <ArrowRight size={18}/></a></section></main>
    <footer className="marketing-footer"><a className="marketing-brand" href="/"><img src="/firstsignal-logo.png" width="32" height="32" alt=""/>FirstSignal</a><p>Early ideas. Meaningful connections.</p><nav aria-label="Footer navigation"><a href="#how-it-works">How it works</a><a href="/signin?return_to=%2Fapp">Sign in</a><a href="/privacy">Privacy</a></nav><small>© {new Date().getFullYear()} FirstSignal</small></footer>
  </div>;
}
