"use client";
import { useCallback,useEffect,useState,type FormEvent } from 'react';
import { formatINR } from '@/lib/data';
type Proposal={version:number;amount:number;terms:string;status:string;mine:boolean};
type Event=Proposal&{author_name:string;created:string};
export default function NegotiationPanel({id}:{id:string}){
 const [data,setData]=useState<{current:Proposal|null;events:Event[]}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[amount,setAmount]=useState(''),[terms,setTerms]=useState(''),[consent,setConsent]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch(`/api/connections?id=${encodeURIComponent(id)}`);const body=await r.json() as {current:Proposal|null;events:Event[];error?:string};if(!r.ok)throw new Error(body.error || "Unable to complete this request.");setData(body);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load proposals.');}},[id]);
 useEffect(()=>{void load()},[load]);
 const write=async(payload:unknown)=>{setBusy(true);setError('');try{const r=await fetch('/api/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await r.json() as {current:Proposal|null;events:Event[];error?:string};if(!r.ok){if(r.status===409)await load();throw new Error(body.error || "Unable to complete this request.")}setData(body);setEditing(false);setConsent(false);}catch(e){setError(e instanceof Error?e.message:'Unable to save proposal.')}finally{setBusy(false)}};
 const proposal=data?.current;
 const start=()=>{setAmount(proposal?String(proposal.amount):'');setTerms(proposal?.terms||'');setConsent(false);setEditing(true)};
 const submit=(e:FormEvent)=>{e.preventDefault();if(!consent){setError('Confirm that this is a non-binding proposal.');return}void write({action:'proposal',id,version:proposal?.version??0,amount:Number(amount),terms,consent:true})};
 return <section className="negotiation-panel"><div className="negotiation-heading"><h3>Private bids & negotiations</h3><button type="button" className="text-button" disabled={busy} onClick={()=>void load()}>Refresh proposals</button></div><p className="subtle">Discuss indicative amounts and terms. Nothing here is a contract, payment instruction or commitment to invest.</p>{error?<p className="notice error-notice" role="alert">{error}</p>:null}{!data?<p role="status">{error?'Proposals unavailable. Use Refresh proposals to retry.':'Loading proposals…'}</p>:<>
 {proposal?<div className="proposal-current"><span className="tag">{proposal.status==='acknowledged'?'Interest acknowledged':proposal.status}</span><h4>{formatINR(proposal.amount)} <small>indicative amount</small></h4><p className="proposal-terms">{proposal.terms}</p><p className="subtle">Version {proposal.version} · {proposal.mine?'Your proposal':'Their proposal'}</p>{proposal.status==='open'?<div className="proposal-actions">{proposal.mine?<button type="button" className="outline-button" disabled={busy} onClick={()=>void write({action:'decision',id,version:proposal.version,status:'withdrawn',consent:true})}>Withdraw bid</button>:<><button type="button" className="primary-button" disabled={busy} onClick={start}>Make a counteroffer</button><button type="button" className="outline-button" disabled={busy} onClick={()=>void write({action:'decision',id,version:proposal.version,status:'acknowledged',consent:true})}>Acknowledge interest</button><button type="button" className="text-button" disabled={busy} onClick={()=>void write({action:'decision',id,version:proposal.version,status:'declined',consent:true})}>Decline</button></>}</div>:null}</div>:<p className="subtle mt-4">No bids yet. Share an indicative proposal to start.</p>}
 {!editing&&proposal?.status!=='open'?<button type="button" className="primary-button mt-4" disabled={busy} onClick={start}>Create a private bid</button>:null}
 {editing?<form onSubmit={submit} className="dialog-form"><div className="field"><label htmlFor="proposal-amount">Indicative amount (INR)</label><input id="proposal-amount" type="number" min={1} max={1000000000} step={1} required value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="field"><label htmlFor="proposal-terms">Proposed terms and next steps</label><textarea id="proposal-terms" required minLength={20} maxLength={3000} rows={4} value={terms} onChange={e=>setTerms(e.target.value)} placeholder="Describe the structure you want to discuss, milestones, assumptions and questions."/></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>This is a non-binding discussion proposal shared only with the other participant. Formal investment agreements happen separately.</span></label><div className="proposal-actions"><button className="primary-button" disabled={busy}>{busy?'Saving…':proposal?.status==='open'?'Send counteroffer':'Send private bid'}</button><button type="button" className="outline-button" onClick={()=>setEditing(false)}>Cancel</button></div></form>:null}
 {data.events.length?<details className="proposal-history"><summary>Negotiation history · {data.events.length} updates</summary>{data.events.map(event=><article key={event.version}><strong>Version {event.version} · {event.mine?'You':event.author_name}</strong><p>{event.status==='open'?'Proposal':event.status==='acknowledged'?'Interest acknowledged':event.status} · {formatINR(event.amount)}</p><p className="proposal-terms">{event.terms}</p><small>{new Date(event.created).toLocaleString('en-IN')}</small></article>)}</details>:null}
 </>}</section>;
}
