"use client";
import {useCallback,useEffect,useState} from 'react';
type Settings={emailEnabled:boolean;emailConfigured:boolean;notifications:{id:string;title:string;status:string;created:string}[]};
export default function NotificationSettings(){
 const [data,setData]=useState<Settings|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch('/api/connections');const body=await r.json() as Settings & {error?:string};if(!r.ok)throw new Error(body.error || "Unable to complete this request.");setData(body);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load notifications.')}},[]);
 useEffect(()=>{void load()},[load]);
 const write=async(payload:unknown)=>{setBusy(true);try{const r=await fetch('/api/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await r.json() as Settings & {error?:string};if(!r.ok)throw new Error(body.error || "Unable to complete this request.");setData(body);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to update notifications.')}finally{setBusy(false)}};
 return <section className="notification-settings"><div className="negotiation-heading"><h2>Connection notifications</h2><button className="text-button" disabled={busy} onClick={()=>void load()}>Refresh notifications</button></div>{error?<p className="notice error-notice" role="alert">{error}</p>:null}{data?<><p className="subtle">Updates for introductions, messages and private proposals. Email includes a link, never your private message content or terms.</p>{!data.emailConfigured?<p className="notice">Email sending is paused until a verified sender and email service are configured. Connection updates still appear below.</p>:null}<label className="consent"><input type="checkbox" checked={data.emailEnabled} disabled={busy} onChange={e=>void write({action:'preferences',enabled:e.target.checked})}/><span>Email me connection updates at my verified account email. I can turn this off anytime.</span></label>{data.emailConfigured&&data.emailEnabled?<button className="outline-button" disabled={busy} onClick={()=>void write({action:'retry'})}>Retry pending email notifications</button>:null}<ul className="notification-list">{data.notifications.map(n=><li key={n.id}><strong>{n.title}</strong><span>{new Date(n.created).toLocaleString('en-IN')} · {n.status==='submitted'?'Submitted to email provider':n.status==='skipped'||!data.emailEnabled?'Email off':'Email pending'}</span></li>)}</ul>{!data.notifications.length?<p className="subtle">No connection updates yet.</p>:null}</>:<p role="status">{error?'Notifications unavailable. Use Refresh notifications to retry.':'Loading notifications…'}</p>}</section>;
}
