import { getAppUser } from "../../auth";
import { notify } from "@/lib/notifications";
import { database } from "@/lib/database";
import { seedProfiles,type Profile } from "@/lib/data";
import { actionSchema } from "@/lib/validation";
export const dynamic="force-dynamic";
type Stored={id:string;owner:string;kind:string;data:string;listed:number;updated:string};
type RequestRow={id:string;sender:string;recipient:string|null;profile_id:string;target_name:string;sender_name:string;message:string;status:string;created:string;updated:string};
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{"Cache-Control":"no-store"}});
function profile(row:Stored,userId?:string):Profile{const data=JSON.parse(row.data);return {...data,id:row.id,kind:row.kind,updates:[],demo:false,mine:row.owner===userId,listed:!!row.listed,updated:row.updated,evidenceDate:data.evidenceDate??""};}
async function state(userId?:string){const db=database();const rows=await db.prepare("SELECT * FROM profiles WHERE listed = 1 ORDER BY updated DESC LIMIT 200").all<Stored>();const all=rows.results.map(r=>profile(r,userId));if(!userId)return {profiles:[...all,...seedProfiles],savedIds:[],myProfiles:[],requests:[]};
const owned=await db.prepare("SELECT * FROM profiles WHERE owner = ? ORDER BY updated DESC").bind(userId).all<Stored>();const myProfiles=owned.results.map(r=>profile(r,userId));
const [saved,requests,notes]=await Promise.all([db.prepare("SELECT profile_id FROM saves WHERE owner = ?").bind(userId).all<{profile_id:string}>(),db.prepare("SELECT * FROM introductions WHERE sender = ? OR recipient = ? ORDER BY created DESC LIMIT 100").bind(userId,userId).all<RequestRow>(),db.prepare("SELECT * FROM (SELECT m.*, ROW_NUMBER() OVER (PARTITION BY m.introduction_id ORDER BY m.created DESC, m.id DESC) AS position FROM messages m WHERE m.introduction_id IN (SELECT id FROM introductions WHERE sender = ? OR recipient = ? ORDER BY created DESC LIMIT 100)) WHERE position <= 100 ORDER BY created ASC").bind(userId,userId).all<{id:string;introduction_id:string;sender:string;sender_name:string;body:string;created:string}>()]);
return {profiles:[...all,...seedProfiles],myProfiles,savedIds:saved.results.map(r=>r.profile_id),requests:requests.results.map(r=>({id:r.id,profileId:r.profile_id,targetName:r.target_name,senderName:r.sender_name,message:r.message,status:r.status,created:r.created,direction:r.recipient===userId?"incoming":"outgoing",messages:notes.results.filter(m=>m.introduction_id===r.id).map(m=>({id:m.id,body:m.body,senderName:m.sender_name,created:m.created,mine:m.sender===userId}))}))};}
export async function GET(){try{const user=await getAppUser();return json(await state(user?.userId));}catch(e){console.error("Workspace read failed",e);return json({error:"We couldn't load your workspace. Please retry."},503);}}
export async function POST(request:Request){let user;try{user=await getAppUser();}catch{console.error("Authentication service unavailable");return json({error:"Sign-in is temporarily unavailable. Please retry."},503);}if(!user)return json({error:"Sign in to save changes."},401);
const origin=request.headers.get("origin");if(!origin || origin!==new URL(request.url).origin)return json({error:"This request couldn't be verified. Reload and try again."},403);
if(Number(request.headers.get("content-length")??0)>20000)return json({error:"This request is too large."},413);
let raw:string;try{raw=await request.text();}catch{return json({error:"Unable to read your request."},400);}if(raw.length>20000)return json({error:"This request is too large."},413);
let parsed;try{parsed=actionSchema.safeParse(JSON.parse(raw));}catch{return json({error:"Please submit valid form information."},400);}if(!parsed.success)return json({error:parsed.error.issues[0]?.message??"Check your form."},400);
try{const db=database();const a=parsed.data;const now=new Date().toISOString();const owner=user.userId;
if(a.action==="profile"){const current=await db.prepare("SELECT id FROM profiles WHERE owner = ? AND kind = ?").bind(owner,a.profile.kind).first<{id:string}>();const id=current?.id??crypto.randomUUID();await db.prepare("INSERT INTO profiles (id,owner,kind,data,listed,updated) VALUES (?,?,?,?,?,?) ON CONFLICT(owner,kind) DO UPDATE SET data=excluded.data,listed=excluded.listed,updated=excluded.updated").bind(id,owner,a.profile.kind,JSON.stringify(a.profile),a.listed?1:0,now).run();}
if(a.action==="save"||a.action==="request"){const seed=seedProfiles.find(p=>p.id===a.profileId);const stored=seed?null:await db.prepare("SELECT * FROM profiles WHERE id = ? AND listed = 1").bind(a.profileId).first<Stored>();if(!seed&&!stored && !(a.action==="save"&&!a.saved))return json({error:"This profile is no longer available."},404);
if(a.action==="save"){if(a.saved){const count=await db.prepare("SELECT COUNT(*) AS n FROM saves WHERE owner = ?").bind(owner).first<{n:number}>();if((count?.n??0)>=200)return json({error:"Your shortlist is full. Remove a saved profile first."},400);await db.prepare("INSERT INTO saves (owner,profile_id,created) VALUES (?,?,?) ON CONFLICT(owner,profile_id) DO NOTHING").bind(owner,a.profileId,now).run();}else await db.prepare("DELETE FROM saves WHERE owner = ? AND profile_id = ?").bind(owner,a.profileId).run();}
else{if(stored?.owner===owner)return json({error:"You cannot request an introduction to your own profile."},400);const target=seed??profile(stored!);const existing=await db.prepare("SELECT id,status FROM introductions WHERE sender = ? AND profile_id = ?").bind(owner,a.profileId).first<{id:string;status:string}>();if(existing)return json({error:"You already have a request for this profile. Find it in Introductions."},409);const count=await db.prepare("SELECT COUNT(*) AS n FROM introductions WHERE sender = ? AND created > ?").bind(owner,new Date(Date.now()-86400000).toISOString()).first<{n:number}>();if((count?.n??0)>=20)return json({error:"You've reached today's request limit. Try again tomorrow."},429);const introductionId=crypto.randomUUID();await db.prepare("INSERT INTO introductions (id,sender,recipient,profile_id,target_name,sender_name,message,status,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(introductionId,owner,stored?.owner??null,target.id,target.name,user.displayName.slice(0,120),a.message,seed?"draft":"pending",now,now).run();await notify(stored?.owner??null,introductionId,"You have a new introduction request");}}
if(a.action==="respond"||a.action==="message"){const intro=await db.prepare("SELECT * FROM introductions WHERE id = ? AND (sender = ? OR recipient = ?)").bind(a.id,owner,owner).first<RequestRow>();if(!intro)return json({error:"This conversation is unavailable."},404);
if(a.action==="respond"){if(intro.status!=="pending")return json({error:"This request is no longer pending."},409);if(a.status==="withdrawn"?intro.sender!==owner:intro.recipient!==owner)return json({error:"You cannot change this request."},403);const result=await db.prepare("UPDATE introductions SET status = ?,updated = ? WHERE id = ? AND status = 'pending'").bind(a.status,now,a.id).run();if(!result.meta.changes)return json({error:"The request changed. Reload to see its status."},409);await notify(intro.sender===owner?intro.recipient:intro.sender,a.id,"Your introduction request has an update");}
else{if(intro.status!=="accepted")return json({error:"Both parties must accept before messaging."},403);const count=await db.prepare("SELECT COUNT(*) AS n FROM messages WHERE introduction_id = ?").bind(a.id).first<{n:number}>();if((count?.n??0)>=100)return json({error:"This pilot conversation has reached its message limit."},400);await db.prepare("INSERT INTO messages (id,introduction_id,sender,sender_name,body,created) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),a.id,owner,user.displayName.slice(0,120),a.body,now).run();await notify(intro.sender===owner?intro.recipient:intro.sender,a.id,"You have a new connection message");}}
return json(await state(owner));}catch(e){console.error("Workspace write failed",e);return json({error:"We couldn't save that change. Your input is still here; please retry."},503);}}
